### ISSUE TITLE
Chrome's "Pepper" (PPAPI) version of the Flash Player stopping recording

### ISSUE THREAD

**Issue by krajewsk** [pauln/moodle-repository_recordaudio#1]
This plugin hangs when "Preparing to upload" in Chrome.  The assignment version has been updated see discussion : https://moodle.org/plugins/view.php?plugin=assignment_onlineaudio

**Comment by pauln** [comment]
Sorry, this issue should have been closed long ago.  The currently available version of this plugin still works in current Chrome, so I guess I must have missed closing this ticket once the recording widget was updated.
