### ISSUE TITLE
How to deinstall your plugin?

### ISSUE THREAD

**Issue by euneuber** [pauln/moodle-repository_recordaudio#2]
One can deinstall most plugins via /admin/plugins.php - but not repositories.
What is the proper way to deinstall your plugin?

There are no data files left...

(rm -r $MOODLE_DIRrepository/recordaudio/ and DELETE FROM mdl_config_plugins WHERE plugin LIKE 'repository_recordaudio'; ??? )

kind regards,
Eugen

**Comment by dredix84** [comment]
To uninstall the plugin, go to Home  ► Site administration  ► Plugins  ► Plugins overview.
Once the page has loaded, locate Online audio recording (assignsubmission_onlineaudio) in the table then click the "Uninstall" link associated with the Online audio recording.

Moodle will uninstall from the database then will ask you to confirm to delete directory.

**Comment by euneuber** [comment]
Thank you
